# Generated by Django 4.1.7 on 2023-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=180),
        ),
    ]
