# Generated by Django 4.1.7 on 2023-03-25 12:06

import TruckOp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemiTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('production_year', models.DateField()),
                ('registration_number', models.CharField(max_length=8, unique=True, validators=[TruckOp.models.registration_num_validator])),
            ],
        ),
    ]
